******************************************************
2019-10-21 10:09:54,684 - INFO - logger - Path for logging: data/outputs/20191021080944/micro_grid_design_logfile.log
2019-10-21 10:09:54,684 - INFO - logger - Used oemof version: 0.2.2
2019-10-21 10:09:54,684 - INFO - A_offgridders_wrapper - 
 
 MICRO GRID TOOL 3.0
 Version: 19.06.2019 
 Coded by: Martha M. Hoffmann 
 Reiner Lemoine Institute (Berlin) 
 
 
2019-10-21 10:09:54,686 - INFO - C_sensitivity_experiments - Parameters of sensitivity analysis
2019-10-21 10:09:54,689 - INFO - C_sensitivity_experiments - Randomized blackout timeseries for all combinations of blackout duration and frequency (1 experiments) will be generated.
2019-10-21 10:09:54,871 - DEBUG - C_sensitivity_experiments - Generating header for results.csv
2019-10-21 10:09:54,908 - INFO - C_sensitivity_experiments - For 1 project sites with 1 scenarios each, 1 sensitivity_experiment_s will be performed for each case.
2019-10-21 10:09:54,911 - INFO - E_blackouts_central_grid - Blackout experiment 1: Blackout duration 2.5 hrs, blackout frequency 0 per month
2019-10-21 10:09:54,911 - INFO - E_blackouts_central_grid - Number of blackouts in simulated timeframe: 0
2019-10-21 10:09:54,912 - INFO - E_blackouts_central_grid - Grid is not operational for 0 hours, with a reliability of 100.0 percent. 

2019-10-21 10:09:54,913 - INFO - E_blackouts_central_grid - Missing blackout timeseries added through auto-generation.
2019-10-21 10:09:55,531 - DEBUG - A_offgridders_wrapper - Using grid availability timeseries that was randomly generated.
2019-10-21 10:09:55,531 - INFO - A_offgridders_wrapper - Starting simulation, project site test_site.
2019-10-21 10:09:55,532 - DEBUG - G1_oemof_create_model - Complete case dictionary:
2019-10-21 10:09:55,532 - DEBUG - G1_oemof_create_model - {'case_name': 'hoevelaken', 'filename': 'hoevelaken', 'total_demand_ac': 512.7284923996475, 'total_demand_dc': 0.0, 'peak_demand': 5.382346945312058, 'evaluated_days': 5, 'genset_with_minimal_loading': False, 'storage_fixed_capacity': False, 'storage_fixed_power': False, 'genset_fixed_capacity': False, 'pv_fixed_capacity': False, 'pcc_consumption_fixed_capacity': None, 'pcc_feedin_fixed_capacity': None, 'wind_fixed_capacity': False, 'rectifier_ac_dc_fixed_capacity': False, 'inverter_dc_ac_fixed_capacity': False, 'allow_shortage': True, 'max_shortage': 0, 'stability_constraint': 'share_hybrid', 'renewable_share_constraint': False, 'number_of_equal_generators': 1, 'evaluation_perspective': 'AC_system', 'force_charge_from_maingrid': False, 'discharge_only_when_blackout': False, 'enable_inverter_only_at_backout': False}
2019-10-21 10:09:55,532 - DEBUG - G1_oemof_create_model - Create oemof model by adding case-specific busses and components.
2019-10-21 10:09:55,534 - DEBUG - G1_oemof_create_model - Added to oemof model: Electricity bus of energy system, AC
2019-10-21 10:09:55,534 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: demand AC
2019-10-21 10:09:55,546 - DEBUG - G1_oemof_create_model - Added to oemof model: Fuel bus
2019-10-21 10:09:55,548 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: source fuel
2019-10-21 10:09:55,551 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: genset oem no minload
2019-10-21 10:09:55,554 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: wind
2019-10-21 10:09:55,559 - DEBUG - G1_oemof_create_model - Added to oemof model: Electricity bus of energy system, DC
2019-10-21 10:09:55,560 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: demand DC
2019-10-21 10:09:55,560 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: pv oem
2019-10-21 10:09:55,562 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: storage oem
2019-10-21 10:09:55,563 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: rectifier oem
2019-10-21 10:09:55,567 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: inverter_dc_ac oem
2019-10-21 10:09:55,568 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: excess
2019-10-21 10:09:55,569 - DEBUG - G2a_oemof_busses_and_componets - Added to oemof model: source shortage
2019-10-21 10:09:55,569 - DEBUG - G1_oemof_create_model - Create oemof model based on created components and busses.
2019-10-21 10:09:55,941 - INFO - G1_oemof_create_model - Added constraint: Stability though actual generation of diesel generators and backup through batteries.
2019-10-21 10:09:56,016 - INFO - G1_oemof_create_model - Simulating...
2019-10-21 10:09:56,017 - WARNING - solvers - Failed to create solver with name 'cbc':
signal only works in main thread
2019-10-21 10:09:56,358 - INFO - _internal - 127.0.0.1 - - [21/Oct/2019 10:09:56] "GET /offgrid_simulator/get_result/20191021080944 HTTP/1.1" 500 -
2019-10-21 10:09:56,438 - ERROR - _internal - Error on request:
Traceback (most recent call last):
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3078, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
KeyError: 'capacity_pv_kWp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/werkzeug/serving.py", line 303, in run_wsgi
    execute(self.server.app)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/werkzeug/serving.py", line 291, in execute
    application_iter = app(environ, start_response)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cabbage/Documents/School/Year3/Internship/LOGiC_Refactored/LOGiCv1.2/logic/offgrid_simulator/controllers.py", line 61, in get_result
    'nominal_solar_power_installed': results['capacity_pv_kWp'][0],
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/frame.py", line 2688, in __getitem__
    return self._getitem_column(key)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/frame.py", line 2695, in _getitem_column
    return self._get_item_cache(key)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/generic.py", line 2489, in _get_item_cache
    values = self._data.get(item)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/internals.py", line 4115, in get
    loc = self.items.get_loc(item)
  File "/home/cabbage/anaconda3/envs/logic-fork/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 3080, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 140, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/index.pyx", line 162, in pandas._libs.index.IndexEngine.get_loc
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 1492, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
  File "pandas/_libs/hashtable_class_helper.pxi", line 1500, in pandas._libs.hashtable.PyObjectHashTable.get_item
    
KeyError: 'capacity_pv_kWp'
